### ISSUE TITLE
unicode error for notebooks with interactive matplotlib figures

### ISSUE THREAD

**Issue by pavoljuhas** [jupyter/nbdime#101]
With active diff driver `git diff HEAD~1` fails for notebooks that contain interactive matplotlib windows, i.e., which start with `%matplotlib notebook`

``` sh
$ git diff HEAD~1

Traceback (most recent call last):
  File "/Users/pjuhas/anaconda/envs/dev/bin/git-nbdiffdriver", line 11, in <module>
    load_entry_point('nbdime', 'console_scripts', 'git-nbdiffdriver')()
  File "/Users/pjuhas/programs/github/jupyter/nbdime/nbdime/gitdiffdriver.py", line 117, in main
    show_diff(opts.a, opts.b)
  File "/Users/pjuhas/programs/github/jupyter/nbdime/nbdime/gitdiffdriver.py", line 75, in show_diff
    nbdiffapp.main([before, after])
  File "/Users/pjuhas/programs/github/jupyter/nbdime/nbdime/nbdiffapp.py", line 119, in main
    r = main_diff(args)
  File "/Users/pjuhas/programs/github/jupyter/nbdime/nbdime/nbdiffapp.py", line 44, in main_diff
    pretty_print_notebook_diff(afn, bfn, a, d)
  File "/Users/pjuhas/programs/github/jupyter/nbdime/nbdime/prettyprint.py", line 331, in pretty_print_notebook_diff
    print("\n".join(p))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2265' in position 1080: ordinal not in range(128)
fatal: external diff died, stopping at test.ipynb
```

The interactive plot window from matplotlib (version 1.5.3) adds the following java code to the notebook:

```
...
       "        alert('Your browser does not have WebSocket support.' +\n",
       "              'Please try Chrome, Safari or Firefox ≥ 6. ' +\n",
...
```

where the `≥` symbol is the \u2265 Unicode character that makes the diff program fail.

**Comment by vidartf** [comment]
Thanks for reporting this! It seems like this happens while printing to the console, so it could be interesting to know what OS and terminal you were using (so we can test any proposed fix). The Python version might be relevant to know as well.

**Comment by pavoljuhas** [comment]
I have seen the problem with the current nbdime (481b2cdc94ec83ce6285ebb8d4bfa7c5995a03ba) using Anaconda Python 2.7.12 on Mac OS X.  I am using the default terminal application, i.e., Terminal 2.5.3.  My language setting is LANG="en_US.UTF-8".

**Comment by rgieseke** [comment]
I had the same error as above using a Python2 based install of `nbdime` with a Python3 notebook containing a unicode character. I resolved the issue by re-installing `nbdime` with Python3. 

Let me know if a detailed example or test case would be helpful.

**Comment by vidartf** [comment]
@rgieseke What OS/terminal are you on?

**Comment by martinal** [comment]
Also a detailed stacktrace would help a lot.

**Comment by rgieseke** [comment]
Unfortunately I can't reproduced the problem now, even after re-installing `nbdime` with Python2. If I get it again I will report. I'm on Linux with xfce4-terminal 0.6.3. I was using doing Matplotlib plots with Unicode chars in labels.

Sorry for the noise and thanks for this amazingly helpful tool!

**Comment by F-A** [comment]
I also ran in the same problem. I'm using nbdime version 1.2, with Python 2, Ubunu 16.04. The Python packages and pip are installed using Anaconda.

Here is the full stacktrace (let me know if you need more information):

> Traceback (most recent call last):
  File "/home/florian/Documents/Code/Python_code/Anaconda/envs/GoNoGo/bin/git-nbdiffdriver", line 11, in <module>
    sys.exit(main())
  File "/home/florian/Documents/Code/Python_code/Anaconda/envs/GoNoGo/lib/python2.7/site-packages/nbdime/gitdiffdriver.py", line 100, in main
    return nbdiffapp.main([opts.a, opts.b])
  File "/home/florian/Documents/Code/Python_code/Anaconda/envs/GoNoGo/lib/python2.7/site-packages/nbdime/nbdiffapp.py", line 85, in main
    return main_diff(arguments)
  File "/home/florian/Documents/Code/Python_code/Anaconda/envs/GoNoGo/lib/python2.7/site-packages/nbdime/nbdiffapp.py", line 53, in main_diff
    pretty_print_notebook_diff(afn, bfn, a, d, Printer())
  File "/home/florian/Documents/Code/Python_code/Anaconda/envs/GoNoGo/lib/python2.7/site-packages/nbdime/prettyprint.py", line 754, in pretty_print_notebook_diff
    pretty_print_diff(a, di, path, out)
  File "/home/florian/Documents/Code/Python_code/Anaconda/envs/GoNoGo/lib/python2.7/site-packages/nbdime/prettyprint.py", line 719, in pretty_print_diff
    pretty_print_dict_diff(a, di, path, out)
  File "/home/florian/Documents/Code/Python_code/Anaconda/envs/GoNoGo/lib/python2.7/site-packages/nbdime/prettyprint.py", line 677, in pretty_print_dict_diff
    pretty_print_diff_entry(a, e, path, out)
  File "/home/florian/Documents/Code/Python_code/Anaconda/envs/GoNoGo/lib/python2.7/site-packages/nbdime/prettyprint.py", line 633, in pretty_print_diff_entry
    pretty_print_diff(a[key], e.diff, nextpath, out)
  File "/home/florian/Documents/Code/Python_code/Anaconda/envs/GoNoGo/lib/python2.7/site-packages/nbdime/prettyprint.py", line 721, in pretty_print_diff
    pretty_print_list_diff(a, di, path, out)
  File "/home/florian/Documents/Code/Python_code/Anaconda/envs/GoNoGo/lib/python2.7/site-packages/nbdime/prettyprint.py", line 683, in pretty_print_list_diff
    pretty_print_diff_entry(a, e, path, out)
  File "/home/florian/Documents/Code/Python_code/Anaconda/envs/GoNoGo/lib/python2.7/site-packages/nbdime/prettyprint.py", line 633, in pretty_print_diff_entry
    pretty_print_diff(a[key], e.diff, nextpath, out)
  File "/home/florian/Documents/Code/Python_code/Anaconda/envs/GoNoGo/lib/python2.7/site-packages/nbdime/prettyprint.py", line 719, in pretty_print_diff
    pretty_print_dict_diff(a, di, path, out)
  File "/home/florian/Documents/Code/Python_code/Anaconda/envs/GoNoGo/lib/python2.7/site-packages/nbdime/prettyprint.py", line 677, in pretty_print_dict_diff
    pretty_print_diff_entry(a, e, path, out)
  File "/home/florian/Documents/Code/Python_code/Anaconda/envs/GoNoGo/lib/python2.7/site-packages/nbdime/prettyprint.py", line 633, in pretty_print_diff_entry
    pretty_print_diff(a[key], e.diff, nextpath, out)
  File "/home/florian/Documents/Code/Python_code/Anaconda/envs/GoNoGo/lib/python2.7/site-packages/nbdime/prettyprint.py", line 721, in pretty_print_diff
    pretty_print_list_diff(a, di, path, out)
  File "/home/florian/Documents/Code/Python_code/Anaconda/envs/GoNoGo/lib/python2.7/site-packages/nbdime/prettyprint.py", line 683, in pretty_print_list_diff
    pretty_print_diff_entry(a, e, path, out)
  File "/home/florian/Documents/Code/Python_code/Anaconda/envs/GoNoGo/lib/python2.7/site-packages/nbdime/prettyprint.py", line 638, in pretty_print_diff_entry
    pretty_print_value_at(e.valuelist, path, ADD, out)
  File "/home/florian/Documents/Code/Python_code/Anaconda/envs/GoNoGo/lib/python2.7/site-packages/nbdime/prettyprint.py", line 397, in pretty_print_value_at
    pretty_print_output(None, output, prefix, out)
  File "/home/florian/Documents/Code/Python_code/Anaconda/envs/GoNoGo/lib/python2.7/site-packages/nbdime/prettyprint.py", line 505, in pretty_print_output
    pretty_print_item(k, v, oprefix, out)
  File "/home/florian/Documents/Code/Python_code/Anaconda/envs/GoNoGo/lib/python2.7/site-packages/nbdime/prettyprint.py", line 422, in pretty_print_item
    pretty_print_dict(v, (), prefix+IND, out)
  File "/home/florian/Documents/Code/Python_code/Anaconda/envs/GoNoGo/lib/python2.7/site-packages/nbdime/prettyprint.py", line 474, in pretty_print_dict
    pretty_print_item(k, v, prefix, out)
  File "/home/florian/Documents/Code/Python_code/Anaconda/envs/GoNoGo/lib/python2.7/site-packages/nbdime/prettyprint.py", line 432, in pretty_print_item
    out.write("%s%s\n" % (prefix+IND, line))
  File "/home/florian/Documents/Code/Python_code/Anaconda/envs/GoNoGo/lib/python2.7/site-packages/nbdime/nbdiffapp.py", line 52, in write
    print(text, end="")
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2265' in position 66: ordinal not in range(128)

**Comment by F-A** [comment]
If you need, I could send you the Notebook per mail.

**Comment by vidartf** [comment]
Can recreate (although with a slightly different trace, but that is expected) by `nbdiff ./nbdime/tests/files/unicode--1.ipynb ./nbdime/tests/files/unicode--2.ipynb`. Is not picked up during unit tests since standard output is captured.

**Comment by minrk** [comment]
#268 should fix this. In the meantime, setting

    export PYTHONIOENCODING=:replace

should allow it to move past the errors with the current release.
