### ISSUE TITLE
git-nbdiffdriver crashes when writing .git/config 

### ISSUE THREAD

**Issue by pavoljuhas** [jupyter/nbdime#103]
After utf-8 fixes in commit f1a348ea64b222e906766f3fc6ef12af6091ed84 `git-nbdiffdriver` crashes with the following error.  This happens in a fresh repository with `.git/config` in pristine state.

``` sh
$ git-nbdiffdriver config --enable
Traceback (most recent call last):
  File "/Users/pjuhas/arch/anaconda/envs/cmi-dev/bin/git-nbdiffdriver", line 11, in <module>
    load_entry_point('nbdime', 'console_scripts', 'git-nbdiffdriver')()
  File "/Users/pjuhas/programs/github/jupyter/nbdime/nbdime/gitdiffdriver.py", line 115, in main
    opts.config_func(opts.global_)
  File "/Users/pjuhas/programs/github/jupyter/nbdime/nbdime/gitdiffdriver.py", line 57, in enable
    f.write('\n*.ipynb\tdiff=jupyternotebook\n')
TypeError: write() argument 1 must be unicode, not str
```

**Comment by martinal** [comment]
Thanks for the report. Should be easy to fix, but also shows we need unit tests to cover the disk io parts better!
