### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by akhmerov** [jupyter/nbdime#192]
I've encountered this error when enabling the diff driver after a fresh pip install:

```bash
sudo -H pip3 install nbdime
[sudo] password: 
Collecting nbdime
  Downloading nbdime-0.1.0b1-py2.py3-none-any.whl (1.7MB)
    100% |████████████████████████████████| 1.7MB 832kB/s 
...
Installing collected packages: colorama, nbdime
Successfully installed colorama-0.3.7 nbdime-0.1.0b1
> git-nbdiffdriver config --enable --global
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/nbdime/utils.py", line 142, in locate_gitattributes
    bpath = check_output(['git', 'config', '--global', 'core.attributesfile'])
NameError: name 'check_output' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/git-nbdiffdriver", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/nbdime/gitdiffdriver.py", line 106, in main
    opts.config_func(opts.global_)
  File "/usr/local/lib/python3.5/dist-packages/nbdime/gitdiffdriver.py", line 36, in enable
    gitattributes = locate_gitattributes(global_)
  File "/usr/local/lib/python3.5/dist-packages/nbdime/utils.py", line 144, in locate_gitattributes
    except CalledProcessError:
NameError: name 'CalledProcessError' is not defined
```

**Comment by martinal** [comment]
Thanks, I've pushed a quickfix to master.

**Comment by akhmerov** [comment]
Thanks for a prompt response. I have verified that the error doesn't occur anymore if using master.
