### ISSUE TITLE
Is there any way to get the url generated by `git difftool --tool nbdime file.ipynb`?

### ISSUE THREAD

**Issue by shuvrobiswas** [jupyter/nbdime#208]
Hi All,

I am trying to use nbdime in an aws instance where I am running a jupyter notebook server.

In that environment when I run `git difftool --tool nbdime file.ipynb` nothing pops up since there is no gui/desktop on an aws server (no ability to open a chrome tab).

In this case, is it possible to get a url, so I can paste it into the browser to see the diff?

Thanks in advance!

**Comment by vidartf** [comment]
I've proposed a change in #209 that will log the URL for easy copy and paste for all entry points that launch a server and then tries to browse to a specific url.

**Comment by shuvrobiswas** [comment]
Hi minrk,

Thanks for the quick update, I am trying to install the latest development version of nbdime on an aws server.

I have nodejs version 7.2.1 and npm version 3.10.10:
[npm-debug.txt](https://github.com/jupyter/nbdime/files/658208/npm-debug.txt)



When I try to install master:

    git clone https://github.com/jupyter/nbdime
    cd nbdime
    pip install -e .

I am getting the following issue

```
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):                 
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (cu
rrent: {"os":"linux","arch":"x64"})                                                                                                
    npm WARN nbdime-webapp@0.1.0 No description                                                                                    
    npm WARN nbdime-webapp@0.1.0 No repository field.                                                                              
    npm WARN nbdime-webapp@0.1.0 No license field.                                                                                 
    npm ERR! Linux 3.13.0-100-generic                                                                                              
    npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"                                                                       
    npm ERR! node v7.2.1                                                                                                           
    npm ERR! npm  v3.10.10                                                                                                         
    npm ERR! code ELIFECYCLE                                                                                                       
                                                                                                                                   
    npm ERR! nbdime@0.1.0 postinstall: `npm dedupe`                                                                                
    npm ERR! Exit status 243                                                                                                       
    npm ERR!                                                                                                                       
    npm ERR! Failed at the nbdime@0.1.0 postinstall script 'npm dedupe'.                                                           
    npm ERR! Make sure you have the latest version of node.js and npm installed.                                                   
    npm ERR! If you do, this is most likely a problem with the nbdime package,                                                     
    npm ERR! not with npm itself.                                                                                                  
    npm ERR! Tell the author that this fails on your system:                                                                       
    npm ERR!     npm dedupe                                                                                                        
    npm ERR! You can get information on how to open an issue for this project with:                                                
    npm ERR!     npm bugs nbdime                                                                                                   
    npm ERR! Or if that isn't available, you can get their info via:                                                               
    npm ERR!     npm owner ls nbdime                                                                                               
    npm ERR! There is likely additional logging output above.                                                                      
                                                                                                                                   
    npm ERR! Please include the following file with any support request:                                                           
    npm ERR!     /home/ubuntu/nbdime/nbdime/webapp/npm-debug.log                                                                   
    rebuilding js and css failed                                                                                                   
    missing files: ['/home/ubuntu/nbdime/nbdime/webapp/static/build/nbdime.js']                                                    
    Traceback (most recent call last):                                                                                             
      File "<string>", line 1, in <module>                                                                                         
      File "/home/ubuntu/nbdime/setup.py", line 283, in <module>                                                                   
        setup(**setup_args)                                                                                                        
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup                                                              
        dist.run_commands()                                                                                                        
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands                                                       
        self.run_command(cmd)                                                                                                      
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command                                                        
        cmd_obj.run()                                                                                                              
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/develop.py", line 34, in run                                 
        self.install_for_development()                                                                                             
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/develop.py", line 119, in install_for_development            
        self.run_command('build_ext')                                                                                              
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command                                                         
        self.distribution.run_command(command)                                                                                     
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command                                                        
        cmd_obj.run()                                                                                                              
      File "/home/ubuntu/nbdime/setup.py", line 92, in run                                                                         
        raise e                                                                                                                    
    subprocess.CalledProcessError: Command '['npm', 'install']' returned non-zero exit status 1                                    
                                                                                                                                   
    ----------------------------------------                                                                                       
Command "/usr/bin/python -c "import setuptools, tokenize; __file__='/home/ubuntu/nbdime/setup.py'; exec(compile(getattr(tokenize, '
open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/ubunt
u/nbdime   
```
