### ISSUE TITLE
nbdiff stumbles on empty file

### ISSUE THREAD

**Issue by pavoljuhas** [jupyter/nbdime#259]
nbdiff 0.1.2 does not seem to handle empty files.  This also happens in `git diff --cached` just after using `git add` on a new notebook.  Diffing commits that add or delete files would likely result in the same error.

```sh
$ nbdiff /dev/null test.ipynb 
Traceback (most recent call last):
  File "/Users/pjuhas/arch/anaconda/envs/cmi-cur/bin/nbdiff", line 6, in <module>
    sys.exit(nbdime.nbdiffapp.main())
  File "/Users/pjuhas/arch/anaconda/envs/cmi-cur/lib/python2.7/site-packages/nbdime/nbdiffapp.py", line 85, in main
    return main_diff(arguments)
  File "/Users/pjuhas/arch/anaconda/envs/cmi-cur/lib/python2.7/site-packages/nbdime/nbdiffapp.py", line 35, in main_diff
    a = nbformat.read(afn, as_version=4)
  File "/Users/pjuhas/arch/anaconda/envs/cmi-cur/lib/python2.7/site-packages/nbformat/__init__.py", line 139, in read
    return read(f, as_version, **kwargs)
  File "/Users/pjuhas/arch/anaconda/envs/cmi-cur/lib/python2.7/site-packages/nbformat/__init__.py", line 141, in read
    return reads(fp.read(), as_version, **kwargs)
  File "/Users/pjuhas/arch/anaconda/envs/cmi-cur/lib/python2.7/site-packages/nbformat/__init__.py", line 74, in reads
    nb = reader.reads(s, **kwargs)
  File "/Users/pjuhas/arch/anaconda/envs/cmi-cur/lib/python2.7/site-packages/nbformat/reader.py", line 58, in reads
    nb_dict = parse_json(s, **kwargs)
  File "/Users/pjuhas/arch/anaconda/envs/cmi-cur/lib/python2.7/site-packages/nbformat/reader.py", line 17, in parse_json
    raise NotJSONError(("Notebook does not appear to be JSON: %r" % s)[:77] + "...")
nbformat.reader.NotJSONError: Notebook does not appear to be JSON: u''...
```

**Comment by vidartf** [comment]
Thanks for you report! I have a few questions to help understand this case: Is the file completely empty (0 size), or simply an empty notebook? And what behavior would you expect from nbdime in your case?

**Comment by vidartf** [comment]
Technical note: As far as I understand git differentiates between empty files (0 size), and non-existing files (references them as `/dev/null`). We currently have a TODO in the code on the latter, but have not considered the former if I am correct.

**Comment by pavoljuhas** [comment]
I originally found this crash when trying out git-nbdiffdriver.  I expect `git diff` should show a full content of any new notebook as added and a full content of any deleted notebook as removed.  This is a common scenario in VCS and the nbdiff driver needs to handle it to be useful.  

Perhaps the nbdiffdriver could fall back to standard git diffs when any of compared files is not a valid notebook format?

I understand `nbdiff` is usually run from command line so it does not need to handle /dev/null if zero-length file is not a valid notebook.  It should however handle invalid files with some informative error message rather than as an uncaught exception.

**Comment by akhmerov** [comment]
Same error appears when a notebook is removed from the repository.

**Comment by vidartf** [comment]
Fix proposed in #261.

**Comment by akhmerov** [comment]
Thanks! Do you plan a patch release soon?

**Comment by vidartf** [comment]
I would maybe like to have #101 and #238 in as well, but if those take longer than expected, it might just be better to iterate with a quick second patch.
