### ISSUE TITLE
updating nbdime dev version fails with npm error

### ISSUE THREAD

**Issue by amueller** [jupyter/nbdime#314]
I've tried to ``pip install -e .`` current master.

It fails with the following log
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/andy/.nvm/versions/node/v7.7.3/bin/node',
1 verbose cli   '/home/andy/.nvm/versions/node/v7.7.3/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@4.1.2
3 info using node@v7.7.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle nbdime-webapp@0.4.0~prebuild: nbdime-webapp@0.4.0
6 silly lifecycle nbdime-webapp@0.4.0~prebuild: no script for prebuild, continuing
7 info lifecycle nbdime-webapp@0.4.0~build: nbdime-webapp@0.4.0
8 verbose lifecycle nbdime-webapp@0.4.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle nbdime-webapp@0.4.0~build: PATH: /home/andy/.nvm/versions/node/v7.7.3/lib/node_modules/npm/bin/node-gyp-bin:/home/andy/checkout/nbdime/nbdime/webapp/node_modules/.bin:/home/andy/.nvm/versions/node/v7.7.3/bin:/home/andy/.npm-global/bin:/home/andy/.gem/ruby/2.3.0/bin:/home/andy/.local/bin:/home/andy/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle nbdime-webapp@0.4.0~build: CWD: /home/andy/checkout/nbdime/nbdime/webapp
11 silly lifecycle nbdime-webapp@0.4.0~build: Args: [ '-c', 'webpack' ]
12 silly lifecycle nbdime-webapp@0.4.0~build: Returned: code: 2  signal: null
13 info lifecycle nbdime-webapp@0.4.0~build: Failed to exec build script
14 verbose stack Error: nbdime-webapp@0.4.0 build: `webpack`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/home/andy/.nvm/versions/node/v7.7.3/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/andy/.nvm/versions/node/v7.7.3/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid nbdime-webapp@0.4.0
16 verbose cwd /home/andy/checkout/nbdime/nbdime/webapp
17 error Linux 4.10.0-37-generic
18 error argv "/home/andy/.nvm/versions/node/v7.7.3/bin/node" "/home/andy/.nvm/versions/node/v7.7.3/bin/npm" "run" "build"
19 error node v7.7.3
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error nbdime-webapp@0.4.0 build: `webpack`
22 error Exit status 2
23 error Failed at the nbdime-webapp@0.4.0 build script 'webpack'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the nbdime-webapp package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs nbdime-webapp
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls nbdime-webapp
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```
I'm sure something is wrong with my npm setup, but I have no idea what...

**Comment by vidartf** [comment]
There is a bit of flux for these things now with #310. I want to wait on debugging this until that is merged.

**Comment by vidartf** [comment]
@amueller Does it work with master now that #310/#297 were merged?

**Comment by vidartf** [comment]
(if not, can you give the output of `pip install -v -e .`?)

**Comment by amueller** [comment]
install worked fine, thanks :)
