### ISSUE TITLE
nbdiff-web crashes with message 500: Internal Server Error

### ISSUE THREAD

**Issue by hsm207** [jupyter/nbdime#328]
When I call nbdiff-web in a directory that has a jupyter notebook, my web browser will open and will start to display a diff. But after a couple of seconds, the display will change to '500: Internal Server Error'.

This is the output from the console:

```python
ERROR:tornado.application:Uncaught exception POST /api/diff?1511453892998 (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:50237', method='POST', uri='/api/diff?1511453892998', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Accept': '*/*', 'Origin': 'http://127.0.0.1:50237', 'Referer': 'http://127.0.0.1:50237/difftool?base=tournament_83.ipynb%20(HEAD)&remote=tournament_83.ipynb', 'Accept-Language': 'en-US,en-MY;q=0.7,en;q=0.3', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063', 'X-Xsrftoken': '2|ee1e39af|555684cbcff1942e7293370b9f1bd64f|1511317618', 'Content-Type': 'text/plain;charset=UTF-8', 'Accept-Encoding': 'gzip, deflate', 'Host': '127.0.0.1:50237', 'Content-Length': '68', 'Dnt': '1', 'Connection': 'Keep-Alive', 'Cache-Control': 'no-cache', 'Cookie': '_xsrf=2|ee1e39af|555684cbcff1942e7293370b9f1bd64f|1511317618'})
Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\lib\site-packages\nbformat\reader.py", line 14, in parse_json
    nb_dict = json.loads(s, **kwargs)
  File "C:\Users\user\Anaconda3\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\user\Anaconda3\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\user\Anaconda3\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "c:\users\user\appdata\local\temp\nbdime\nbdime\webapp\nbdimeserver.py", line 206, in post
    base_nb = self.get_notebook_argument('base')
  File "c:\users\user\appdata\local\temp\nbdime\nbdime\webapp\nbdimeserver.py", line 226, in get_notebook_argument
    return nbformat.read(arg, as_version=4)
  File "C:\Users\user\Anaconda3\lib\site-packages\nbformat\__init__.py", line 141, in read
    return reads(fp.read(), as_version, **kwargs)
  File "C:\Users\user\Anaconda3\lib\site-packages\nbformat\__init__.py", line 74, in reads
    nb = reader.reads(s, **kwargs)
  File "C:\Users\user\Anaconda3\lib\site-packages\nbformat\reader.py", line 58, in reads
    nb_dict = parse_json(s, **kwargs)
  File "C:\Users\user\Anaconda3\lib\site-packages\nbformat\reader.py", line 17, in parse_json
    raise NotJSONError(("Notebook does not appear to be JSON: %r" % s)[:77] + "...")
nbformat.reader.NotJSONError: Notebook does not appear to be JSON: ''...
ERROR:tornado.access:500 POST /api/diff?1511453892998 (127.0.0.1) 38.11ms
```

The version of the notebook server I am running is 5.2.1 and its running on this version of Python:

`Python 3.6.3 |Anaconda custom (64-bit)| (default, Nov  8 2017, 15:10:56) [MSC v.1900 64 bit (AMD64)]`

Both the pip and development version of nbdime gives the same error.

**Comment by xtotdam** [comment]
Same on Miniconda 2 (Python 2.7.12)
Yet I don't see any diff, it crashes instantly.
Console `nbdime diff` works nice.

```
Traceback (most recent call last):
  File "c:\miniconda2\lib\site-packages\tornado\web.py", line 1467, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "c:\miniconda2\lib\site-packages\nbdime\webapp\nbdimeserver.py", line 145, in get
    mathjax_config=self.mathjax_config,
AttributeError: 'MainDiffHandler' object has no attribute 'mathjax_config'
```

**Comment by vidartf** [comment]
@xtotdam Your issue was because nbdime was relying on a feature that was not present until 5.0 of the notebook package. I've submitted a PR for that in #329.

**Comment by vidartf** [comment]
@hsm207 I'm not able to reproduce your issue. Could you specify exactly what command you are using, and preferably share the notebook in question (or a repo with a commit to get the diff in question if you are using a repo controlled notebook)?

**Comment by vidartf** [comment]
@hsm207 After some further digging, I was able to reproduce the behavior:

This issue only appears when trying to load the diff view of files in git history for a second time. The file handles needed to be reset before they could be used again. Out of curiosity, what usage pattern caused you to come across this behavior?

**Comment by hsm207** [comment]
@vidartf How do I reset the file handles?

My usage pattern is that in my project, I have code written in python scripts and jupyter notebooks. When I work on the python scripts, I commit using Pycharm's git integration. When I need to commit the jupyter notebooks, I open a console and launch nbdiff-web to view the changes to be committed.

**Comment by vidartf** [comment]
@hsm207 I added the code in #333. It basically ensures that it seeks to the start of the file before attempting to read it with nbformat. Hopefully we'll be able to release that within a week!

**Comment by hsm207** [comment]
Thanks @vidartf!
