### ISSUE TITLE
Error from web-based viewers if using Jinja2<=2.8

### ISSUE THREAD

**Issue by dberenbaum** [jupyter/nbdime#343]
The web-based viewer raises a `TemplateAssertionError` if the installed version of `jinja2` <= 2.8. Could a minimum version >=2.9 be added to `setup.py`? Example traceback:

```
Traceback (most recent call last):
  File "/Users/dave/anaconda3/envs/nbdime/lib/python2.7/site-packages/tornado/web.py", line 1510, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/Users/dave/anaconda3/envs/nbdime/lib/python2.7/site-packages/nbdime/webapp/nbdimeserver.py", line 154, in get
    mathjax_config=self.mathjax_config,
  File "/Users/dave/anaconda3/envs/nbdime/lib/python2.7/site-packages/notebook/base/handlers.py", line 424, in render_template
    return template.render(**ns)
  File "/Users/dave/anaconda3/envs/nbdime/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/dave/anaconda3/envs/nbdime/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/dave/anaconda3/envs/nbdime/lib/python2.7/site-packages/nbdime/webapp/templates/nbdimepage.html", line 28, in <module>
    <script id='nbdime-config-data' type="application/json">{{ config_data|tojson|safe }}</script>
TemplateAssertionError: no filter named 'tojson'
```

**Comment by vidartf** [comment]
Thanks for the report! I've put in a lower version bound in #344.
