### ISSUE TITLE
Marges fail with an assertion violation

### ISSUE THREAD

**Issue by gramster** [jupyter/nbdime#373]
I have a three notebooks that I have split into two versions each, one version being a blog post with all the cells executed, and the other version being for interactive use by those who want to use the notebook that way. I have a parent version from when the split originally happened. Sometimes I change the blog post version, and sometimes I change the interactive version, and I want to merge the changes from one to the other. There are some small differences between them (e.g. the blog post version refers to itself as a "post" while the interactive version refers to itself as a "notebook").

One of the three is working fine when I do merges, but for the other two I get the issue below:

```
Traceback (most recent call last):
  File "/Users/gram/anaconda/bin/nbmerge", line 11, in <module>
    sys.exit(main())
  File "/Users/gram/anaconda/lib/python3.6/site-packages/nbdime/nbmergeapp.py", line 136, in main
    return main_merge(arguments)
  File "/Users/gram/anaconda/lib/python3.6/site-packages/nbdime/nbmergeapp.py", line 51, in main_merge
    merged, decisions = merge_notebooks(b, l, r, args)
  File "/Users/gram/anaconda/lib/python3.6/site-packages/nbdime/merging/notebooks.py", line 181, in merge_notebooks
    decisions = decide_notebook_merge(base, local, remote, args)
  File "/Users/gram/anaconda/lib/python3.6/site-packages/nbdime/merging/notebooks.py", line 155, in decide_notebook_merge
    strategies)
  File "/Users/gram/anaconda/lib/python3.6/site-packages/nbdime/merging/generic.py", line 767, in decide_merge_with_diff
    path, parent_decisions, strategies)
  File "/Users/gram/anaconda/lib/python3.6/site-packages/nbdime/merging/generic.py", line 742, in _merge
    path, decisions, strategies)
  File "/Users/gram/anaconda/lib/python3.6/site-packages/nbdime/merging/generic.py", line 297, in _merge_dicts
    subdecisions = _merge(bv, ld.diff, rd.diff, item_path, decisions, strategies)
  File "/Users/gram/anaconda/lib/python3.6/site-packages/nbdime/merging/generic.py", line 746, in _merge
    path, decisions, strategies)
  File "/Users/gram/anaconda/lib/python3.6/site-packages/nbdime/merging/generic.py", line 658, in _merge_lists
    base, d0, d1, path, decisions, item_strategy)
  File "/Users/gram/anaconda/lib/python3.6/site-packages/nbdime/merging/generic.py", line 439, in _merge_concurrent_inserts
    item_strategy)
  File "/Users/gram/anaconda/lib/python3.6/site-packages/nbdime/merging/generic.py", line 414, in _split_addrange
    assert local_items == remote_items
AssertionError
```

**Comment by vidartf** [comment]
Thanks for the report! Which version of nbdime is this (`nbdime --version`)? Would you mind trying the release candidate for 1.0 (`pip install --pre nbdime`)?

**Comment by gramster** [comment]
0.4.1.

The release candidate seems to work. 🥇
