### ISSUE TITLE
Error 500: in «path_list, attr, info = [s.decode('utf8', 'replace') for s in spec.split(b'\x00')[:3]]»

### ISSUE THREAD

**Issue by belonesox** [jupyter/nbdime#417]
Got Error 500 clicking on "git" button:
```
E 2018-08-17 21:40:03.384 SingleUserNotebookApp web:1670] Uncaught exception POST /user/sfomin/nbdime/api/diff?1534531163171 (172.31.1.3)
    HTTPServerRequest(protocol='http', host='science-test.office.custis.ru', method='POST', uri='/user/sfomin/nbdime/api/diff?1534531163171', version='HTTP/1.1', remote_ip='172.31.1.3')
    Traceback (most recent call last):
      File "/usr/lib64/python3.6/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/usr/lib64/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/usr/lib64/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
        yielded = next(result)
      File "/usr/lib/python3.6/site-packages/nbdime/webapp/nb_server_extension.py", line 151, in post
        base_nb, remote_nb = self._get_git_notebooks(base[len('git:'):])
      File "/usr/lib/python3.6/site-packages/nbdime/webapp/nb_server_extension.py", line 97, in _get_git_notebooks
        for fbase, fremote in changed_notebooks('HEAD', None, base, git_root):
      File "/usr/lib/python3.6/site-packages/nbdime/gitfiles.py", line 160, in changed_notebooks
        entry.b_path, entry.b_blob, ref_remote, repo_dir)
      File "/usr/lib/python3.6/site-packages/nbdime/gitfiles.py", line 110, in _get_diff_entry_stream
        ret = apply_possible_filter(path)
      File "/usr/lib/python3.6/site-packages/nbdime/vcs/git/filter_integration.py", line 68, in apply_possible_filter
        filter_attr = interrogate_filter(git_path)
      File "/usr/lib/python3.6/site-packages/nbdime/vcs/git/filter_integration.py", line 28, in interrogate_filter
        path_list, attr, info = [s.decode('utf8', 'replace') for s in spec.split(b'\x00')[:3]]
    ValueError: not enough values to unpack (expected 3, got 1)
```

Looks like obvious lack of exception handling in 
https://github.com/jupyter/nbdime/blob/fb6484a0b3acdd50f7961a9c7fb9f0db5f74c55d/nbdime/vcs/git/filter_integration.py#L25

In my case ``check_output`` returns non-splitted line:
```
>>> spec = check_output(['git', 'check-attr', '-z', 'filter', 'test.ipynb'])
>>> spec
b'test.ipynb: filter: unspecified\n'
>>> spec.split(b'\x00')[:3]
[b'test.ipynb: filter: unspecified\n']
```

**Comment by belonesox** [comment]
*And what is your OS?*
Latest Centos 7
```
# uname -a
Linux science-test 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

*Which version of git do you have?*
```
# rpm -qa | grep "git-"
git-1.8.3.1-14.el7_5.x86_64
```

**Comment by vidartf** [comment]
Hmm.. It seems this feature (`-z` for machine formatted output) was added initially in [git version 1.8.5](https://git-scm.com/docs/git-check-attr/1.8.5). Is 1.8.3 the latest available version of git on your OS?

**Comment by belonesox** [comment]
Yes, for Centos 7, in standard and EPEL repositories 1.8.3 git is latest.
https://centos.pkgs.org/7/centos-updates-x86_64/

Yes it possible to install  "sclo-git212" or "sclo-git25" from "CentOS SCLo x86_64"  + symlinks ... 
but it is very ugly way.

**Comment by vidartf** [comment]
@belonesox Do you have any idea if the output format of this command (`git check-attr`) changed a lot previous to 1.8.5? If it was reasonably stable, we could add some special case logic for parsing it. In general though, I would also recommend pushing centos to update their version of git.

**Comment by vidartf** [comment]
Closing as won't fix, but if someone else wants to contribute a fix a PR is welcome!
