### ISSUE TITLE
git-nbdiffdriver: UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 12: ordinal not in range(128)

### ISSUE THREAD

**Issue by Hubbitus** [jupyter/nbdime#452]
```
$ cat .gitattributes
*.ipynb diff=jupyternotebook
*.ipynb merge=jupyternotebook
```
```
$ git diff
Traceback (most recent call last):
  File "/usr/bin/git-nbdiffdriver", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/nbdime/vcs/git/diffdriver.py", line 121, in main
    return nbdiffapp.main_diff(opts)
  File "/usr/lib/python2.7/site-packages/nbdime/nbdiffapp.py", line 46, in main_diff
    return _handle_diff(base, remote, output, args)
  File "/usr/lib/python2.7/site-packages/nbdime/nbdiffapp.py", line 87, in _handle_diff
    pretty_print_notebook_diff(base_name, remote_name, a, d, config)
  File "/usr/lib/python2.7/site-packages/nbdime/prettyprint.py", line 860, in pretty_print_notebook_diff
    afn=afn, bfn=bfn, atime=atime, btime=btime))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 12: ordinal not in range(128)
fatal: external diff died, stopping at docker/BeakerX/notebooks/Основы статистики - степик курс.ipynb
```

Please note direct invoke: `nbdiff Основы\ статистики\ -\ степик\ курс.ipynb` works as expected

**Comment by vidartf** [comment]
Hi, and thanks for your report! For reproducibility, could you share the output of:
```bash
nbdime --version
git --version
```

**Comment by Hubbitus** [comment]
Sure:
```
$ nbdime --version
1.0.4
$ git --version
git version 2.20.1
```

**Comment by Hubbitus** [comment]
It works now. Thank you.
