### ISSUE TITLE
No module named git

### ISSUE THREAD

**Issue by Hubbitus** [jupyter/nbdime#509]
```
$ sudo pip install nbdime --upgrade
$ nbdiff
Traceback (most recent call last):
  File "/usr/bin/nbdiff", line 7, in <module>
    from nbdime.nbdiffapp import main
  File "/usr/lib/python2.7/site-packages/nbdime/nbdiffapp.py", line 15, in <module>
    from .args import (
  File "/usr/lib/python2.7/site-packages/nbdime/args.py", line 18, in <module>
    from .gitfiles import is_gitref
  File "/usr/lib/python2.7/site-packages/nbdime/gitfiles.py", line 11, in <module>
    from git import (
ImportError: No module named git
```

nbdime-1.1.0-py2.py3-none-any.whl

**Comment by vidartf** [comment]
Try `pip install GitPython`. That is the package which is supposed to supply that import.

**Comment by vidartf** [comment]
Closing as answered.
