### ISSUE TITLE
File not found during enabling nbdiff git integration

### ISSUE THREAD

**Issue by mghijs** [jupyter/nbdime#564]
```
Traceback (most recent call last):
  File "c:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\Scripts\nbdime.exe\__main__.py", line 7, in <module>
  File "c:\anaconda3\lib\site-packages\nbdime\__main__.py", line 95, in main_dispatch
    diff_driver(args) or
  File "c:\anaconda3\lib\site-packages\nbdime\vcs\git\diffdriver.py", line 128, in main
    opts.config_func(opts.scope)
  File "c:\anaconda3\lib\site-packages\nbdime\vcs\git\diffdriver.py", line 41, in enable
    check_call(cmd + ['diff.jupyternotebook.command', 'git-nbdiffdriver diff'])
  File "c:\anaconda3\lib\subprocess.py", line 342, in check_call
    retcode = call(*popenargs, **kwargs)
  File "c:\anaconda3\lib\subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\anaconda3\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\anaconda3\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Het systeem kan het opgegeven bestand niet vinden
```

on:
```
     active environment : base
    active env location : C:\Anaconda3
            shell level : 1
       user config file : C:\Users\Administrator\.condarc
 populated config files : C:\Users\Administrator\.condarc
          conda version : 4.9.2
    conda-build version : 3.18.8
         python version : 3.7.3.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Anaconda3\pkgs
                          C:\Users\Administrator\.conda\pkgs
                          C:\Users\Administrator\AppData\Local\conda\conda\pkgs
       envs directories : C:\Anaconda3\envs
                          C:\Users\Administrator\.conda\envs
                          C:\Users\Administrator\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.9.2 requests/2.25.0 CPython/3.7.3 Windows/10 Windows/10.0.18362
          administrator : True
             netrc file : None
           offline mode : False
```

Would someone be able to help me, please? Thank you.

**Comment by vidartf** [comment]
It might be a permission problem (I see you are running as the Administrator user). Does using an admin cmd resolve it?

**Comment by mghijs** [comment]
Thank you @vidartf , I was running Anaconda prompt as admin already as running it for my own user gave the same error. The Windows admin cmd returns the following error however:

```
C:\Users\mjghijs\AppData\Roaming\Python\Python37>nbdime config-git --enable --system
Traceback (most recent call last):
  File "c:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\Scripts\nbdime.exe\__main__.py", line 7, in <module>
  File "c:\anaconda3\lib\site-packages\nbdime\__main__.py", line 89, in main_dispatch
    from nbdime.vcs.git.difftool import main as diff_tool
  File "c:\anaconda3\lib\site-packages\nbdime\vcs\git\difftool.py", line 23, in <module>
    from nbdime.webapp import nbdifftool
  File "c:\anaconda3\lib\site-packages\nbdime\webapp\nbdifftool.py", line 13, in <module>
    from .nbdimeserver import main_server as run_server
  File "c:\anaconda3\lib\site-packages\nbdime\webapp\nbdimeserver.py", line 15, in <module>
    from notebook.base.handlers import IPythonHandler, APIHandler
  File "c:\anaconda3\lib\site-packages\notebook\base\handlers.py", line 22, in <module>
    from tornado import web, gen, escape, httputil
  File "c:\anaconda3\lib\site-packages\tornado\web.py", line 87, in <module>
    from tornado.httpserver import HTTPServer
  File "c:\anaconda3\lib\site-packages\tornado\httpserver.py", line 29, in <module>
    import ssl
  File "c:\anaconda3\lib\ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: DLL load failed: Kan opgegeven module niet vinden.
```

**Comment by vidartf** [comment]
This seems hard for me to say anything informed about, as it seems to be a more generic problem with your Python install, and not nbdime in particular (in this case, it seems to be a problem with the SSL lib).

**Comment by mghijs** [comment]
I will test it when I do a fresh install, nothing seems to work at the moment (although I can import SSL). Thank you for your help

**Comment by vidartf** [comment]
Thanks for the extra feedback. Will close this as answered for now :)
