### ISSUE TITLE
nbdime jupyterlab extension doesn't work correctly with Jupyter 3 and nodejs 14

### ISSUE THREAD

**Issue by Mycron** [jupyter/nbdime#570]
Hi, guys!
I'm experiencing trouble using nbdime-jupyterlab@2.1.0-beta.1 with jupyter 3.0.5
Here is a stacktrace given from running jupyterlab session:
`Traceback (most recent call last):
      File "/opt/python/3.7.7/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/opt/python/3.7.7/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/opt/python/3.7.7/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/python/3.7.7/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 252, in get
        extensions = yield self.manager.list_extensions()
      File "/opt/python/3.7.7/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/opt/python/3.7.7/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/python/3.7.7/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 252, in get
        extensions = yield self.manager.list_extensions()
      File "/opt/python/3.7.7/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/opt/python/3.7.7/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/python/3.7.7/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 119, in list_extensions
        pkg_info = yield self._get_pkg_info(name, data)
      File "/opt/python/3.7.7/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/opt/python/3.7.7/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/python/3.7.7/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 119, in list_extensions
        pkg_info = yield self._get_pkg_info(name, data)
      File "/opt/python/3.7.7/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/opt/python/3.7.7/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/python/3.7.7/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 190, in _get_pkg_info
        outdated = yield self._get_outdated()
      File "/opt/python/3.7.7/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/opt/python/3.7.7/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/python/3.7.7/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 190, in _get_pkg_info
        outdated = yield self._get_outdated()
      File "/opt/python/3.7.7/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/opt/python/3.7.7/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/python/3.7.7/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 224, in _load_outdated
        app_options=self.app_options
      File "/opt/python/3.7.7/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/opt/python/3.7.7/lib/python3.7/concurrent/futures/_base.py", line 428, in result
        return self.__get_result()
      File "/opt/python/3.7.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
        raise self._exception
      File "/opt/python/3.7.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/python/3.7.7/lib/python3.7/site-packages/jupyterlab/commands.py", line 546, in get_latest_compatible_package_versions
        return handler.latest_compatible_package_versions(names)
      File "/opt/python/3.7.7/lib/python3.7/site-packages/jupyterlab/commands.py", line 1809, in latest_compatible_package_versions
        raise ValueError(msg % keys)
    ValueError: "['nbdime-jupyterlab@2.1.0-beta.1']" is not a valid npm package
[W 2021-03-05 11:44:07.541 LabApp] Unhandled error`

Details about platform:

- Jupyterlab 3.0.5
- nodejs 14.16
- python 3.7.7
- jupyterlab/git v0.30.0-beta.2

**Comment by Mycron** [comment]
Update:
I've got correctly working extension by using particular version of nbdime-jupyterlab npm package with:
`npm install nbdime-jupyterlab@2.0.1`

**Comment by vidartf** [comment]
Version 3.0.0 was released today with support for lab 3.
