### ISSUE TITLE
Cannot run nbdime 3.0.0 with JL 3.x

### ISSUE THREAD

**Issue by DarkmatterVale** [jupyter/nbdime#591]
Hello,

When I install nbime v3.0.0 on JL 3.0.14, I get the following error when trying to run jupyterlab:

```
[jovyan@0a4aa6d92c4d ~]$ jupyter lab
/usr/local/lib/python3.7/site-packages/jupyter_server/transutils.py:13: FutureWarning: The alias `_()` will be deprecated. Use `_i18n()` instead.
  warnings.warn(warn_msg, FutureWarning)
[I 2021-05-10 23:26:03.818 ServerApp] jupyter_server_mathjax | extension was successfully linked.
[I 2021-05-10 23:26:03.818 ServerApp] jupyter_server_proxy | extension was successfully linked.
[I 2021-05-10 23:26:03.829 ServerApp] jupyterlab | extension was successfully linked.
[I 2021-05-10 23:26:03.839 ServerApp] Writing notebook server cookie secret to /home/jovyan/.jupyter_runtime/jupyter_cookie_secret
[W 2021-05-10 23:26:04.362 ServerApp] 'ExtensionManager' object has no attribute '_extensions'
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-lab", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/jupyter_server/extension/application.py", line 518, in launch_instance
    serverapp = cls.initialize_server(argv=args)
  File "/usr/local/lib/python3.7/site-packages/jupyter_server/extension/application.py", line 491, in initialize_server
    find_extensions=find_extensions,
  File "</opt/amazon/lib/python3.7/site-packages/decorator.py:decorator-gen-7>", line 2, in initialize
  File "/opt/amazon/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jupyter_server/serverapp.py", line 1849, in initialize
    self.init_server_extensions()
  File "/usr/local/lib/python3.7/site-packages/jupyter_server/serverapp.py", line 1698, in init_server_extensions
    self.extension_manager.link_all_extensions(self)
  File "/usr/local/lib/python3.7/site-packages/jupyter_server/extension/manager.py", line 354, in link_all_extensions
    self.link_extension(name, serverapp)
  File "/usr/local/lib/python3.7/site-packages/jupyter_server/extension/manager.py", line 327, in link_extension
    extension = self.extensions[name]
  File "/usr/local/lib/python3.7/site-packages/nbclassic/nbserver.py", line 80, in extensions
    nb = self._extensions.get("nbclassic")
AttributeError: 'ExtensionManager' object has no attribute '_extensions'
```

I have confirmed that my setup works when I install like so: `pip install nbdime==2.1.0` and does not work when I install a newer version: `pip install nbdime==3.0.0`

**Comment by vidartf** [comment]
There might be a mismatch between the versions of your dependencies. Would you mind sharing the output of `pip freeze`?

**Comment by DarkmatterVale** [comment]
Appears that root cause was the recent `nbclassic` package release (see https://github.com/jupyterlab/jupyterlab/issues/10228 for more information). Everything is back to working now.

**Comment by vidartf** [comment]
Thanks for cross-linking! 👍
