### ISSUE TITLE
Strange behavior with KeyboardInterrupt that I don't understand

### ISSUE THREAD

**Issue by fperez** [jupyter/nbdime#616]
I'm running nbdime in a JupyterHub with URL proxying, so I wanted to wrap the call in a convenience wrapper for my students. But strangely, when I run this little script:

```python
#!/usr/bin/env python

import sys
from subprocess import run

print(sys.executable)

cmd = ['nbdiff-web', '--ip', '0.0.0.0', '-p', '9999', '--base-url',
       '/user/$JUPYTERHUB_USER/proxy/absolute/9999']

cmd.extend(sys.argv[1:])
print(f'running {cmd}')

try:
    run(cmd)
except KeyboardInterrupt:
    print("Closing nbdiff")
    sys.exit(0)
```

the traceback from `Ctrl-C` is still printed:

```
(base) (main)jupyter-fernando-2eperez[jupyter-vc]> nbdiff-hub nb1.ipynb nb2.ipynb 
/srv/conda/bin/python
running ['nbdiff-web', '--ip', '0.0.0.0', '-p', '9999', '--base-url', '/user/$JUPYTERHUB_USER/proxy/absolute/9999', 'nb1.ipynb', 'nb2.ipynb']
[I nbdimeserver:416] Listening on 0.0.0.0, port 9999
[W webutil:18] No web browser found: could not locate runnable browser.
[I webutil:29] URL: http://127.0.0.1:9999/user/$JUPYTERHUB_USER/proxy/absolute/9999/diff?base=nb1.ipynb&remote=nb2.ipynb

^CTraceback (most recent call last):
  File "/srv/conda/envs/notebook/bin/nbdiff-web", line 10, in <module>
    sys.exit(main())
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/nbdime/webapp/nbdiffweb.py", line 96, in main
    return main_diff(opts)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/nbdime/webapp/nbdiffweb.py", line 83, in main_diff
    return run_server(
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/nbdime/webapp/nbdimeserver.py", line 438, in main_server
    io_loop.start()
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "/srv/conda/envs/notebook/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/srv/conda/envs/notebook/lib/python3.9/asyncio/base_events.py", line 1854, in _run_once
    event_list = self._selector.select(timeout)
  File "/srv/conda/envs/notebook/lib/python3.9/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
Closing nbdiff
(base) (main)jupyter-fernando-2eperez[jupyter-vc]> 
```

In order to supress the traceback I had to add this block instead of using the standard `try/except` approach:

```
import signal
signal.signal(signal.SIGINT, lambda x, y: sys.exit(0))
```

That did work, but I'm baffled. What is nbdime doing internally that could cause this traceback to propagate through?  Right now I don't have time to look at the code so I figured I'd ask here, but I can try to dig deeper later on.

Thanks for any input!

**Comment by fperez** [comment]
ah, nvm - the tb is coming from inside the nbdime subprocess, I'm a dummy. Sorry for the noise, all good!

**Comment by vidartf** [comment]
Sure! FYI, I think you should be able to import `main` from nbdime.webapp.nbdiffweb, and pass the argv along. Then you should be able to catch the interrupt!

**Comment by fperez** [comment]
Thx for the tip @vidartf! I hadn't dug into the code to look for a pure python entry point, but I'm glad to hear that it exists. That might make it a little easier to integrate with the url proxying in hosted hubs!
