### ISSUE TITLE
Failed in CLI command , using flag `config-git`

### ISSUE THREAD

**Issue by Kimdongui** [jupyter/nbdime#621]
Hello 👋,  I m currently enjoying this tool but I have some trouble using it  

My property is
```
OS : macOS 12.3.1
python : 3.8.12
virtual-environment : pyenv
```
I installed your features by using below command and it seems well
```zsh
> pip install nbdime
Collecting nbdime
  Using cached nbdime-3.1.1-py2.py3-none-any.whl (5.3 MB)
Collecting GitPython!=2.1.4,!=2.1.5,!=2.1.6
  Using cached GitPython-3.1.27-py3-none-any.whl (181 kB)
Collecting nbformat
  Using cached nbformat-5.3.0-py3-none-any.whl (73 kB)
Collecting colorama
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting pygments
  Using cached Pygments-2.11.2-py3-none-any.whl (1.1 MB)
Collecting tornado
  Using cached tornado-6.1-cp38-cp38-macosx_10_9_x86_64.whl (416 kB)
Collecting jupyter-server-mathjax>=0.2.2
  Using cached jupyter_server_mathjax-0.2.5-py3-none-any.whl (3.1 MB)
Collecting requests
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting jinja2>=2.9
  Using cached Jinja2-3.1.1-py3-none-any.whl (132 kB)
Collecting jupyter-server
  Using cached jupyter_server-1.16.0-py3-none-any.whl (343 kB)
Collecting gitdb<5,>=4.0.1
  Using cached gitdb-4.0.9-py3-none-any.whl (63 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.1-cp38-cp38-macosx_10_9_x86_64.whl (13 kB)
Collecting packaging
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting prometheus-client
  Using cached prometheus_client-0.14.1-py3-none-any.whl (59 kB)
Collecting Send2Trash
  Using cached Send2Trash-1.8.0-py3-none-any.whl (18 kB)
Collecting argon2-cffi
  Using cached argon2_cffi-21.3.0-py3-none-any.whl (14 kB)
Collecting jupyter-client>=6.1.12
  Using cached jupyter_client-7.2.2-py3-none-any.whl (130 kB)
Collecting websocket-client
  Using cached websocket_client-1.3.2-py3-none-any.whl (54 kB)
Collecting pyzmq>=17
  Using cached pyzmq-22.3.0-cp38-cp38-macosx_10_9_x86_64.whl (1.3 MB)
Collecting jupyter-core>=4.7.0
  Using cached jupyter_core-4.9.2-py3-none-any.whl (86 kB)
Collecting terminado>=0.8.3
  Using cached terminado-0.13.3-py3-none-any.whl (14 kB)
Collecting nbconvert>=6.4.4
  Using cached nbconvert-6.5.0-py3-none-any.whl (561 kB)
Collecting anyio>=3.1.0
  Using cached anyio-3.5.0-py3-none-any.whl (79 kB)
Collecting traitlets>=5.1.0
  Using cached traitlets-5.1.1-py3-none-any.whl (102 kB)
Collecting jsonschema>=2.6
  Using cached jsonschema-4.4.0-py3-none-any.whl (72 kB)
Collecting fastjsonschema
  Using cached fastjsonschema-2.15.3-py3-none-any.whl (22 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting sniffio>=1.1
  Using cached sniffio-1.2.0-py3-none-any.whl (10 kB)
Collecting smmap<6,>=3.0.1
  Using cached smmap-5.0.0-py3-none-any.whl (24 kB)
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
  Using cached pyrsistent-0.18.1-cp38-cp38-macosx_10_9_universal2.whl (81 kB)
Collecting importlib-resources>=1.4.0
  Using cached importlib_resources-5.7.1-py3-none-any.whl (28 kB)
Collecting attrs>=17.4.0
  Using cached attrs-21.4.0-py2.py3-none-any.whl (60 kB)
Collecting nest-asyncio>=1.5.4
  Using cached nest_asyncio-1.5.5-py3-none-any.whl (5.2 kB)
Collecting python-dateutil>=2.8.2
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting entrypoints
  Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
Collecting beautifulsoup4
  Using cached beautifulsoup4-4.11.1-py3-none-any.whl (128 kB)
Collecting defusedxml
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Collecting jupyterlab-pygments
  Using cached jupyterlab_pygments-0.2.2-py2.py3-none-any.whl (21 kB)
Collecting pandocfilters>=1.4.1
  Using cached pandocfilters-1.5.0-py2.py3-none-any.whl (8.7 kB)
Collecting tinycss2
  Using cached tinycss2-1.1.1-py3-none-any.whl (21 kB)
Collecting bleach
  Using cached bleach-5.0.0-py3-none-any.whl (160 kB)
Collecting nbclient>=0.5.0
  Using cached nbclient-0.6.0-py3-none-any.whl (70 kB)
Collecting mistune<2,>=0.8.1
  Using cached mistune-0.8.4-py2.py3-none-any.whl (16 kB)
Collecting ptyprocess
  Using cached ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Collecting argon2-cffi-bindings
  Using cached argon2_cffi_bindings-21.2.0-cp38-abi3-macosx_10_9_universal2.whl (53 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Using cached pyparsing-3.0.8-py3-none-any.whl (98 kB)
Collecting zipp>=3.1.0
  Using cached zipp-3.8.0-py3-none-any.whl (5.4 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting cffi>=1.0.1
  Using cached cffi-1.15.0-cp38-cp38-macosx_10_9_x86_64.whl (178 kB)
Collecting soupsieve>1.2
  Using cached soupsieve-2.3.2.post1-py3-none-any.whl (37 kB)
Collecting webencodings
  Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Installing collected packages: webencodings, Send2Trash, ptyprocess, mistune, fastjsonschema, certifi, zipp, websocket-client, urllib3, traitlets, tornado, tinycss2, soupsieve, sniffio, smmap, six, pyzmq, pyrsistent, pyparsing, pygments, pycparser, prometheus-client, pandocfilters, nest-asyncio, MarkupSafe, jupyterlab-pygments, idna, entrypoints, defusedxml, colorama, charset-normalizer, attrs, terminado, requests, python-dateutil, packaging, jupyter-core, jinja2, importlib-resources, gitdb, cffi, bleach, beautifulsoup4, anyio, jupyter-client, jsonschema, GitPython, argon2-cffi-bindings, nbformat, argon2-cffi, nbclient, nbconvert, jupyter-server, jupyter-server-mathjax, nbdime
Successfully installed GitPython-3.1.27 MarkupSafe-2.1.1 Send2Trash-1.8.0 anyio-3.5.0 argon2-cffi-21.3.0 argon2-cffi-bindings-21.2.0 attrs-21.4.0 beautifulsoup4-4.11.1 bleach-5.0.0 certifi-2021.10.8 cffi-1.15.0 charset-normalizer-2.0.12 colorama-0.4.4 defusedxml-0.7.1 entrypoints-0.4 fastjsonschema-2.15.3 gitdb-4.0.9 idna-3.3 importlib-resources-5.7.1 jinja2-3.1.1 jsonschema-4.4.0 jupyter-client-7.2.2 jupyter-core-4.9.2 jupyter-server-1.16.0 jupyter-server-mathjax-0.2.5 jupyterlab-pygments-0.2.2 mistune-0.8.4 nbclient-0.6.0 nbconvert-6.5.0 nbdime-3.1.1 nbformat-5.3.0 nest-asyncio-1.5.5 packaging-21.3 pandocfilters-1.5.0 prometheus-client-0.14.1 ptyprocess-0.7.0 pycparser-2.21 pygments-2.11.2 pyparsing-3.0.8 pyrsistent-0.18.1 python-dateutil-2.8.2 pyzmq-22.3.0 requests-2.27.1 six-1.16.0 smmap-5.0.0 sniffio-1.2.0 soupsieve-2.3.2.post1 terminado-0.13.3 tinycss2-1.1.1 tornado-6.1 traitlets-5.1.1 urllib3-1.26.9 webencodings-0.5.1 websocket-client-1.3.2 zipp-3.8.0
```

But when I try to use `nbdime config-git --enable` then I have failed with following msg
```zsh
> nbdime config-git --enable
Traceback (most recent call last):
  File "/Users/donghyunkim/.pyenv/versions/nbdime/bin/nbdime", line 8, in <module>
    sys.exit(main_dispatch())
  File "/Users/donghyunkim/.pyenv/versions/3.8.12/envs/nbdime/lib/python3.8/site-packages/nbdime/__main__.py", line 82, in main_dispatch
    from nbdime.vcs.git.diffdriver import main as diff_driver
  File "/Users/donghyunkim/.pyenv/versions/3.8.12/envs/nbdime/lib/python3.8/site-packages/nbdime/vcs/git/diffdriver.py", line 26, in <module>
    from nbdime.args import (
  File "/Users/donghyunkim/.pyenv/versions/3.8.12/envs/nbdime/lib/python3.8/site-packages/nbdime/args.py", line 13, in <module>
    from .config import (
  File "/Users/donghyunkim/.pyenv/versions/3.8.12/envs/nbdime/lib/python3.8/site-packages/nbdime/config.py", line 4, in <module>
    from ipython_genutils import py3compat
ModuleNotFoundError: No module named 'ipython_genutils'
```
I tried to find something from your docs but I can't find clue that solves my problem

So, I guess several questions
1. Should I pre-install `jupyter` or other packages?
    - (I think installation should contains related packages like `ipython_genutils`)
2. How to know `config-git` command usage

Thank you for reading
Have a nice day!

**Comment by minrk** [comment]
This was fixed by #618, we just need to make a release.
