### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by mgorny** [jupyter/nbdime#653]
Could you make a new release, please? The current version is from Oct 2021. It seems that a lot of fixes have landed since, and there was no new activity for a while.

**Comment by fperez** [comment]
I wanted to quickly check on this - for a few weeks I'd been relying on installing from git, but as of today it stopped working as it seems something changed in the JS dependencies:

```
      > nbdime@6.1.2 build
      > tsc --project . && node scripts/copy-files.js

      lerna ERR! npm run build exited 1 in 'nbdime-webapp'
      lerna ERR! npm run build stdout:

      > build
      > webpack -p

      lerna ERR! npm run build stderr:
      ModuleNotFoundError: Module not found: Error: Can't resolve 'lib0/logging' in '/private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/yjs/dist'
          at /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/webpack/lib/Compilation.js:925:10
          at /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/webpack/lib/NormalModuleFactory.js:401:22
          at /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/webpack/lib/NormalModuleFactory.js:130:21
          at /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/webpack/lib/NormalModuleFactory.js:224:22
          at /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/neo-async/async.js:2830:7
          at /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/neo-async/async.js:6877:13
          at /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/webpack/lib/NormalModuleFactory.js:214:25
          at /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/enhanced-resolve/lib/Resolver.js:213:14
          at /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/enhanced-resolve/lib/Resolver.js:285:5
          at eval (eval at create (/private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
          at /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
          at /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/enhanced-resolve/lib/Resolver.js:285:5
          at eval (eval at create (/private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
          at /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/enhanced-resolve/lib/Resolver.js:285:5
          at eval (eval at create (/private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
          at /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
          at /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/enhanced-resolve/lib/Resolver.js:285:5
          at eval (eval at create (/private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:43:1)
          at /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:30:40
          at /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/enhanced-resolve/lib/Resolver.js:285:5
          at eval (eval at create (/private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
          at /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/enhanced-resolve/lib/Resolver.js:285:5
          at eval (eval at create (/private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
          at /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/enhanced-resolve/lib/forEachBail.js:30:14
          at /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/enhanced-resolve/lib/Resolver.js:285:5
          at eval (eval at create (/private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
          at /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
          at /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/enhanced-resolve/lib/Resolver.js:285:5
          at eval (eval at create (/private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
          at /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/enhanced-resolve/lib/Resolver.js:285:5
          at eval (eval at create (/private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
          at /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
          at /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/enhanced-resolve/lib/Resolver.js:285:5
          at eval (eval at create (/private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
          at /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/enhanced-resolve/lib/RootPlugin.js:37:38
          at _next42 (eval at create (/private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)
      resolve 'lib0/logging' in '/private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/yjs/dist'
        Parsed request is a module
        using description file: /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/yjs/package.json (relative path: ./dist)
          Field 'browser' doesn't contain a valid alias configuration
          resolve as module
            /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/yjs/dist/node_modules doesn't exist or is not a directory
            /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/yjs/node_modules doesn't exist or is not a directory
            /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/node_modules doesn't exist or is not a directory
            /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/node_modules doesn't exist or is not a directory
            /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/node_modules doesn't exist or is not a directory
            /private/var/folders/_c/node_modules doesn't exist or is not a directory
            /private/var/folders/node_modules doesn't exist or is not a directory
            /private/var/node_modules doesn't exist or is not a directory
            /private/node_modules doesn't exist or is not a directory
            /node_modules doesn't exist or is not a directory
            looking for modules in /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules
              using description file: /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/package.json (relative path: ./node_modules)
                Field 'browser' doesn't contain a valid alias configuration
                using description file: /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/lib0/package.json (relative path: ./logging)
                  no extension
                    Field 'browser' doesn't contain a valid alias configuration
                    /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/lib0/logging doesn't exist
                  .webpack.js
                    Field 'browser' doesn't contain a valid alias configuration
                    /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/lib0/logging.webpack.js doesn't exist
                  .web.js
                    Field 'browser' doesn't contain a valid alias configuration
                    /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/lib0/logging.web.js doesn't exist
                  .ts
                    Field 'browser' doesn't contain a valid alias configuration
                    /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/lib0/logging.ts doesn't exist
                  .js
                    Field 'browser' doesn't contain a valid alias configuration
                    /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/lib0/logging.js doesn't exist
                  as directory
                    /private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/node_modules/lib0/logging doesn't exist
      lerna ERR! npm run build exited 1 in 'nbdime-webapp'
      lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
      Traceback (most recent call last):
        File "/Users/fperez/local/conda/envs/testnbd/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/fperez/local/conda/envs/testnbd/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/fperez/local/conda/envs/testnbd/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-build-env-zhgvpx5t/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 413, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-build-env-zhgvpx5t/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 398, in _build_with_temp_dir
          self.run_setup()
        File "/private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-build-env-zhgvpx5t/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 175, in <module>
        File "/private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-build-env-zhgvpx5t/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-build-env-zhgvpx5t/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-build-env-zhgvpx5t/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-build-env-zhgvpx5t/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-build-env-zhgvpx5t/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-build-env-zhgvpx5t/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/setupbase.py", line 484, in run
          [self.run_command(cmd) for cmd in cmds]
        File "/private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/setupbase.py", line 484, in <listcomp>
          [self.run_command(cmd) for cmd in cmds]
        File "/private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-build-env-zhgvpx5t/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-build-env-zhgvpx5t/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-build-env-zhgvpx5t/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/setupbase.py", line 267, in run
          c.run()
        File "/private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/setupbase.py", line 385, in run
          run(npm_cmd + ['run', build_cmd], cwd=node_package)
        File "/private/var/folders/_c/4j20b5zn1k515sp7q7y8bkt40000gv/T/pip-req-build-rglctaac/setupbase.py", line 208, in run
          return subprocess.check_call(cmd, **kwargs)
        File "/Users/fperez/local/conda/envs/testnbd/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/usr/local/bin/npm', 'run', 'build']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for nbdime
```

Pinging @ryanlovett @facusapienza21 as this is what's blocking our JupyterLab 3.6.2 update (I can't get our image to build anymore).

**Comment by vidartf** [comment]
3.2.0 released, thanks for the patience!
