### ISSUE TITLE
Diff-web not working

### ISSUE THREAD

**Issue by user799595** [jupyter/nbdime#655]
Hello,

I installed nbdime 3.1.1 and ran
```
$ nbdime diff-web demo.ipynb demo_diff.ipynb
[I nbdimeserver:422] Listening on 127.0.0.1, port 54752
[I webutil:29] URL: http://127.0.0.1:54752/diff?base=demo.ipynb&remote=demo_diff.ipynb
[W warnings:109] /lib/python3.10/site-packages/jupyter_server/base/handlers.py:240: UserWarning: The Tornado web application does not have an 'identity_provider' defined in its settings. In future releases of jupyter_server, this will be a required key for all subclasses of `JupyterHandler`. For an example, see the jupyter_server source code for how to add an identity provider to the tornado settings: https://github.com/jupyter-server/jupyter_server/blob/v2.0.0/jupyter_server/serverapp.py#L242
  warnings.warn(

[E web:1798] Uncaught exception GET /diff?base=demo.ipynb&remote=demo_diff.ipynb (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:54752', method='GET', uri='/diff?base=demo.ipynb&remote=demo_diff.ipynb', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/lib/python3.10/site-packages/tornado/web.py", line 1692, in _execute
    result = await result
  File "/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 608, in prepare
    _user = await _user
  File "/lib/python3.10/site-packages/jupyter_server/auth/identity.py", line 240, in _get_user
    _cookie_user = self.get_user_cookie(handler)
  File "/lib/python3.10/site-packages/jupyter_server/auth/identity.py", line 398, in get_user_cookie
    _user_cookie = handler.get_secure_cookie(
  File "/lib/python3.10/site-packages/tornado/web.py", line 773, in get_secure_cookie
    self.require_setting("cookie_secret", "secure cookies")
  File "/lib/python3.10/site-packages/tornado/web.py", line 1592, in require_setting
    raise Exception(
Exception: You must define the 'cookie_secret' setting in your application to use secure cookies
[E web:1221] Uncaught exception in write_error
Traceback (most recent call last):
  File "/lib/python3.10/site-packages/tornado/web.py", line 1692, in _execute
    result = await result
  File "/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 608, in prepare
    _user = await _user
  File "/lib/python3.10/site-packages/jupyter_server/auth/identity.py", line 240, in _get_user
    _cookie_user = self.get_user_cookie(handler)
  File "/lib/python3.10/site-packages/jupyter_server/auth/identity.py", line 398, in get_user_cookie
    _user_cookie = handler.get_secure_cookie(
  File "/lib/python3.10/site-packages/tornado/web.py", line 773, in get_secure_cookie
    self.require_setting("cookie_secret", "secure cookies")
  File "/lib/python3.10/site-packages/tornado/web.py", line 1592, in require_setting
    raise Exception(
Exception: You must define the 'cookie_secret' setting in your application to use secure cookies

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lib/python3.10/site-packages/tornado/web.py", line 1219, in send_error
    self.write_error(status_code, **kwargs)
  File "/lib/python3.10/site-packages/nbdime/webapp/nbdimeserver.py", line 72, in write_error
    return super(NbdimeHandler, self).write_error(status_code, **kwargs)
  File "/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 705, in write_error
    html = self.render_template("%s.html" % status_code, **ns)
  File "/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 631, in render_template
    ns.update(self.template_namespace)
  File "/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 641, in template_namespace
    logged_in=self.logged_in,
  File "/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 185, in logged_in
    user = self.current_user
  File "/lib/python3.10/site-packages/tornado/web.py", line 1345, in current_user
    self._current_user = self.get_current_user()
  File "/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 164, in get_current_user
    raise RuntimeError(msg)
RuntimeError: Calling `MainDiffHandler.get_current_user()` directly is deprecated in jupyter-server 2.0. Use `self.current_user` instead (works in all versions).
[E log:97] {
  "Host": "127.0.0.1:54752",
  "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
}
[E log:98] 500 GET /diff?base=demo.ipynb&remote=demo_diff.ipynb (@127.0.0.1) 3.62ms referer=None
```

Am I doing something wrong?

**Comment by user799595** [comment]
Duplicate: https://github.com/jupyter/nbdime/issues/645
