### ISSUE TITLE
Cannot run `nbdiff-web` `jinja2.exceptions.TemplateNotFound: error.html`

### ISSUE THREAD

**Issue by this-josh** [jupyter/nbdime#749]
I have created a clean conda `3.12.2` env and installed `nbdime==4.0.1`.

I have then created a clean git repo, a and committed a notebook called `a.ipynb`. Now, after changing the notebook and running `nbdiff-web a.ipynb`

I get the error

```python 
[I nbdimeserver:430] Listening on 127.0.0.1, port 58036
[I webutil:29] URL: http://127.0.0.1:58036/difftool
[E web:1875] Uncaught exception GET /difftool (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:58036', method='GET', uri='/difftool', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/private/tmp/.venv/lib/python3.12/site-packages/tornado/web.py", line 1769, in _execute
    result = await result  # type: ignore
             ^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 642, in prepare
    return web.authenticated(lambda _: super().prepare())(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
    url = self.get_login_url()
          ^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/tornado/web.py", line 1443, in get_login_url
    self.require_setting("login_url", "@tornado.web.authenticated")
  File "/private/tmp/.venv/lib/python3.12/site-packages/tornado/web.py", line 1673, in require_setting
    raise Exception(
Exception: You must define the 'login_url' setting in your application to use @tornado.web.authenticated
[E web:1300] Uncaught exception in write_error
Traceback (most recent call last):
  File "/private/tmp/.venv/lib/python3.12/site-packages/tornado/web.py", line 1769, in _execute
    result = await result  # type: ignore
             ^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 642, in prepare
    return web.authenticated(lambda _: super().prepare())(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/tornado/web.py", line 3289, in wrapper
    url = self.get_login_url()
          ^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/tornado/web.py", line 1443, in get_login_url
    self.require_setting("login_url", "@tornado.web.authenticated")
  File "/private/tmp/.venv/lib/python3.12/site-packages/tornado/web.py", line 1673, in require_setting
    raise Exception(
Exception: You must define the 'login_url' setting in your application to use @tornado.web.authenticated

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/tmp/.venv/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 738, in write_error
    html = self.render_template("%s.html" % status_code, **ns)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 665, in render_template
    template = self.get_template(name)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 660, in get_template
    return self.settings["jinja2_env"].get_template(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: 500.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/tmp/.venv/lib/python3.12/site-packages/tornado/web.py", line 1298, in send_error
    self.write_error(status_code, **kwargs)
  File "/private/tmp/.venv/lib/python3.12/site-packages/nbdime/webapp/nbdimeserver.py", line 68, in write_error
    return super(NbdimeHandler, self).write_error(status_code, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 740, in write_error
    html = self.render_template("error.html", **ns)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 665, in render_template
    template = self.get_template(name)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 660, in get_template
    return self.settings["jinja2_env"].get_template(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error.html
[E log:97] {
  "Host": "127.0.0.1:58036",
  "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
  "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
}
[E log:98] 500 GET /difftool (@127.0.0.1) 22.21ms referer=None
^CTraceback (most recent call last):
  File "/private/tmp/.venv/bin/nbdiff-web", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/nbdime/webapp/nbdiffweb.py", line 96, in main
    return main_diff(opts)
           ^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/nbdime/webapp/nbdiffweb.py", line 82, in main_diff
    return handle_gitrefs(base, remote, path, opts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/nbdime/webapp/nbdiffweb.py", line 64, in handle_gitrefs
    status = run_server(
             ^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/site-packages/nbdime/webapp/nbdimeserver.py", line 446, in main_server
    io_loop.start()
  File "/private/tmp/.venv/lib/python3.12/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/private/tmp/.venv/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
    self._run_once()
  File "/private/tmp/.venv/lib/python3.12/asyncio/base_events.py", line 1947, in _run_once
    event_list = self._selector.select(timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.12/selectors.py", line 566, in select
    kev_list = self._selector.control(None, max_ev, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
```

This is on macOS 14.3.1

**Comment by yan12125** [comment]
Seems related to the latest jupyter-server. I can get it working with `pip install 'jupyter-server==2.12.5'`.

**Comment by guilherme-francisco** [comment]
> Seems related to the latest jupyter-server. I can get it working with `pip install 'jupyter-server==2.12.5'`.

It fixed my problem. Thanks!

**Comment by krassowski** [comment]
It looks like `login_url` setting is not getting passed for auth handlers in nbdime. For reference the [jupyter-server passes](https://github.com/jupyter-server/jupyter_server/blob/0adfb2a06a0ffc4c669c6d8d3aa729fd0ba1f8ce/jupyter_server/serverapp.py#L427):

```
"login_url": url_path_join(base_url, "/login"),
```

I think it should be added somewhere here:

https://github.com/jupyter/nbdime/blob/9a02e0d9d69d14c9d6a071016e2f4b08770874f8/nbdime/webapp/nbdimeserver.py#L382-L397

**Comment by yan12125** [comment]
Is login necessary for nbdime? I can get it working by adding `'allow_unauthenticated_access': True` to the aforementioned settings dictionary.

**Comment by stefanzero** [comment]
When will this be fixed in the version of `nbdime` installed by Brew on OSX (Monterey)?

**Comment by krassowski** [comment]
Login is not necessary but authentication is necessary. Setting `allow_unauthenticated_access` to True will prevent jupyter-server from detecting insecure endpoints. This can lead to security vulnerabilities, so the suggestion from https://github.com/jupyter/nbdime/issues/749#issuecomment-2001967952 should not be merged into the code base.

**Comment by etep** [comment]
I hit this issue, and currently I have `jupyter_server==2.14.1`.  The comment trail above indicates the issue is closed, but it's not clear what the fix is. My takeaway... to fix, one must either:
1. roll back jupyter server to an older version, or
2. clone & patch the nbdime repo to be insecure (but how insecure is this... I'm running all this on my machine).

**Comment by krassowski** [comment]
> The comment trail above indicates the issue is closed

The issue is not closed.

Looking at this again, the entire `nbdimeserver` would need to be rewritten to use an `ExtensionApp` to be reasonably secure and avoid code duplication. I changed my mind and no think that short-term adding `allow_unauthenticated_access` is fine as long as it is explicitly documented.

**Comment by greglank** [comment]
I would like to confirm that
(a) This issue is still open, and prevents running nbdiff-web on my local Windows machine
(b) Rolling back jupyter server, `pip install 'jupyter-server==2.12.5'`, worked for me

**Comment by krassowski** [comment]
Can you try `nbdime` [`v4.0.2`](https://github.com/jupyter/nbdime/releases/tag/v4.0.2)?
