### ISSUE TITLE
nbdiff-web <file-path> inside a git repo shows the spinner

### ISSUE THREAD

**Issue by pinchedsquare** [jupyter/nbdime#776]
Installed pip package is: 

Name: nbdime
Version: 4.0.2

I have also ran: 
`nbdime config-git --enable` for my repo. 

when I run `nbdiff-web <file-path>` browser open correctly but there is a spinner and it shows no diff. 

I have tried many combos, it looks like the only way I can get nbdiff-web to show diff is if I save the different revision of the files using `git show` in temporary files and then run `nbdiff-web <old_tmp_file> <new_tmp_file>

I am not sure why diffing with my remote repo doesn't work. 

screenshot of `nbdime show <file-path>` working fine. 
![Image](https://github.com/user-attachments/assets/d16e3b39-c0fd-4509-a1ab-347f35856086)

Screenshot of the issue: 
![Image](https://github.com/user-attachments/assets/ffc19538-fcee-488c-a716-909ba3e99334)

Any help is greatly appreciated.

**Comment by adam-kosinski** [comment]
I had a similar issue where it got stuck on loading in this way because of an error thrown by the javascript code. There was an error in the javascript console that helped me debug (so perhaps take a look at the javascript console?). The issue ended up being some weird line-indexing bug where adding text after a latex section caused a range error. So I just added the text in a new cell instead. It was odd that this happened in nbdiff-web but not in the console nbdiff.

**Comment by steco** [comment]
This is reproducable with a single cell Notebook, attached are 

- `base.ipynb`
- `working.change.ipynb` - which correctly shows up in `nbdiff-web`
- `not.working.change.ipynb` - which causes the hanging

For record, the console error I see is

`Uncaught (in promise) RangeError: Invalid line number 2 in 1-line document
    at r.line (index.js:18:19)
    at Af (range.ts:114:14)
    at ch.buildLineEffects (mergeview.ts:982:32)
    at ch.updateHighlighting (mergeview.ts:1124:63)
    at ch.updateView (mergeview.ts:691:10)
    at ch.init (mergeview.ts:659:10)
    at new Ah (mergeview.ts:1673:12)
    at lh (mergeview.ts:583:19)
    at Uh.createView (cell.ts:293:17)
    at Uh.init (cell.ts:108:37)`

[base.ipynb.txt](https://github.com/user-attachments/files/20140223/base.ipynb.txt)
[not.working.change.ipynb.txt](https://github.com/user-attachments/files/20140222/not.working.change.ipynb.txt)
[working.change.ipynb.txt](https://github.com/user-attachments/files/20140221/working.change.ipynb.txt)
